### PR TITLE
Show object locations

### PR DESCRIPTION
**Pull request by kjell**
Where do we want to show the object location? Now that we have content covering the whole museum, it's pretty important. Here's a first pass: it shows the text location under the object title, and an image of the gallery map under the About text.

image

image

### CODE REVIEW

**Comment by niffur** [comment]
I think this looks good, For the "Gallery XXX" underneath the map, let's capitalize "Gallery" and bold the entire thing.

Located in **Gallery 357**

**Comment by kjell** [comment]
Great. Centered vs. left?

image

image

**Comment by niffur** [comment]
I like it! Looks good both ways, but centering it really puts the focus on it. Can we try a 1px border around the map? It kind of blends into the background in a way that makes it harder to get your bearings on the map. Something light like #ddd or #ccc should be enough to orient you.

**Comment by kjell** [comment]
I went crazy and added a `border-top`

image

**Comment by niffur** [comment]
Ausgezeichnet!

**Comment by damnabit** [comment]
Looks clear, I like it centered and the boarder as well.

**Comment by kjell** [comment]
(if I hadn't looked that up I would have thought it meant gesundheit)

**Pull request closed without merging**
